// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEww_Wu-wLVVfNqqvE52NS-lMiiK2mPIQ',
    appId: '1:149053234633:web:1b6397a4fa70d3adb5dc18',
    messagingSenderId: '149053234633',
    projectId: 'chat-app-bfc64',
    authDomain: 'chat-app-bfc64.firebaseapp.com',
    storageBucket: 'chat-app-bfc64.firebasestorage.app',
    measurementId: 'G-6K9V1WW6ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY0fDeVekfdztMs8kI8lNiqI0wU_zUeUg',
    appId: '1:149053234633:android:63e25b40d4580008b5dc18',
    messagingSenderId: '149053234633',
    projectId: 'chat-app-bfc64',
    storageBucket: 'chat-app-bfc64.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4wE3X9t3e7aHrU2_tnw96KMeEo5vIiYo',
    appId: '1:149053234633:ios:5b39bf72c962e64db5dc18',
    messagingSenderId: '149053234633',
    projectId: 'chat-app-bfc64',
    storageBucket: 'chat-app-bfc64.firebasestorage.app',
    iosBundleId: 'com.example.chatappcleen',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4wE3X9t3e7aHrU2_tnw96KMeEo5vIiYo',
    appId: '1:149053234633:ios:5b39bf72c962e64db5dc18',
    messagingSenderId: '149053234633',
    projectId: 'chat-app-bfc64',
    storageBucket: 'chat-app-bfc64.firebasestorage.app',
    iosBundleId: 'com.example.chatappcleen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEww_Wu-wLVVfNqqvE52NS-lMiiK2mPIQ',
    appId: '1:149053234633:web:a4ba864de5df5070b5dc18',
    messagingSenderId: '149053234633',
    projectId: 'chat-app-bfc64',
    authDomain: 'chat-app-bfc64.firebaseapp.com',
    storageBucket: 'chat-app-bfc64.firebasestorage.app',
    measurementId: 'G-92KBD0Y4Y4',
  );
}
